# Only trigger CI builds for the master branch, instead 
# of every branch. You'll automatically be configured to 
# build PRs, but you can't currently control that from the YAML directly
# For details, see https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers
trigger:
- master

# We can run multiple jobs in parallel. For this project
# I'm running Linux, Windows, and macOS jobs. For syntac details
# see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases
jobs:

# Run a build on macOS at the same time
- job: macOS
  pool:
    vmImage: 'xcode9-macos10.13'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.500'
  - bash: ./build.sh --target=azure-pipeline
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
  - task: CmdLine@2
    inputs:
      script: 'dotnet reportgenerator "-reports:../../coverage/*.xml" "-targetdir:../../coverage/html" -reporttypes:HtmlInline_AzurePipelines "-assemblyfilters:+Shorthand.*"' 
      workingDirectory: 'test/Shorthand.RssFilter.Tests/'
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'cobertura'
      summaryFileLocation: 'coverage/results.cobertura.xml'
      reportDirectory: 'coverage/html'

# Run a build on Windows at the same time
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.500'
  - powershell: .\build.ps1 -Target azure-pipeline
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
  - task: CmdLine@2
    inputs:
      script: 'dotnet reportgenerator "-reports:../../coverage/*.xml" "-targetdir:../../coverage/html" -reporttypes:HtmlInline_AzurePipelines "-assemblyfilters:+Shorthand.*"' 
      workingDirectory: 'test/Shorthand.RssFilter.Tests/'
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'cobertura'
      summaryFileLocation: 'coverage\results.cobertura.xml'
      reportDirectory: 'coverage\html'